apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: app1-env
spec:
  selector:
    matchLabels:
      role: app1
  env:
    - name: COMPANY_NAME
      value: "Oracle India Pvt Ltd." 
