ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  # Kubernetes Master Server
  config.vm.define "kmasterv18" do |kmaster|
    kmaster.vm.box = "centos/7"
    kmaster.vm.hostname = "kmasterv18"
    kmaster.vm.network "private_network", ip: "192.168.76.20"
    kmaster.vm.provider "virtualbox" do |v|
      v.name = "kmasterv18"
      v.memory = 3548
      v.cpus = 2
      # Prevent VirtualBox from interfering with host audio stack
      v.customize ["modifyvm", :id, "--audio", "none"]
    end
    kmaster.vm.provision "shell", path: "bootstrap_kmaster.sh"
  end
 end