apiVersion: v1
kind: Pod
metadata:
  name: my-empty-dir
  labels:
    app: empty-dir
spec:
  containers:
  - image: alpine 
    name: test-container-1

    command: [ 'sh', '-c', 'echo Running alpine container 1; sleep 3600']

    volumeMounts:
    - mountPath: /cache1
      name: cache-volume

  - image: alpine
    name: test-container-2

    command: ['sh', '-c', 'echo Running container 2; sleep 3600']

    volumeMounts:
    - mountPath: /cache2
      name: cache-volume

  volumes:
  - name: cache-volume
    emptyDir: {}
