kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: devs
  name: simple-pod-developers
subjects:
  - kind: Group
    name: devs
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: simple-pod-developer
  apiGroup: rbac.authorization.k8s.io