ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  NodeCount = 1

  # Kubernetes Worker Nodes
  (1..NodeCount).each do |i|
    config.vm.define "ckahaworker#{i}" do |workernode|
      workernode.vm.box = "centos/7"
      workernode.vm.hostname = "ckahaworker#{i}"
      workernode.vm.network "private_network", ip: "192.168.76.15#{i+3}"
      workernode.vm.provider "virtualbox" do |v|
        v.name = "ckahaworker#{i}"
        v.memory = 2024
        v.cpus = 1
        # Prevent VirtualBox from interfering with host audio stack
        v.customize ["modifyvm", :id, "--audio", "none"]
      end
      workernode.vm.provision "shell", path: "bootstrap_kworker.sh"
    end
  end
 end